### PR TITLE
Update Mapsforge-Applications.md

### PR DESCRIPTION
**Pull request by nsoriaresearch**
Added reference to n*soria Fitness, a research project developing a GPS bike computer, activity tracker, map and navigation application

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks for the info.

The name of the app should be fixed "n*soria Fitness" or update the application order in list?

**Comment by nsoriaresearch** [comment]
The entire research project runs under the title n*soria ( n - unlimited number of sensors, -soria - expression of euphoria, success, utopia.)
Either title, n*soria or n*soria fitness is great, the "*" sign didnt translate properly. Thank you.

**Comment by devemux86** [comment]
Then we need to sort the app properly based on its title.

**Comment by nsoriaresearch** [comment]
Sounds good. Thank you.

**Comment by nsoriaresearch** [comment]
> The name of the app should be fixed "n*soria Fitness" or update the application order in list?

"n*soria Fitness" would be the proper name, but as most listings, directories or app stores don't work well with the asterisk, just nsoria or nsoria Fitness (without the asterisk) shall be perfectly fine.

**Comment by devemux86** [comment]
Thanks, reordered and merged via 890ff7855f789aaf793dc535433e04a51d7a60ce.

**Pull request closed without merging**
