### PR TITLE
Cluster-Marker Example 

### PR DESCRIPTION
**Pull request by vennekamp**
Hi, I've created an example for clustering markers. It's working and I did not experience an bugs :-) Nevertheless, code might still need some improvements, since I'm not a professional programmer.

From my point of view, the software is working and I stopped working on this. Thus, I would like to hand it back to you and I like to remove my fork.

Regards, Martin Vennekamp

### CODE REVIEW

**Comment by ludwigb** [comment]
Thanks for your contribution, these are always welcome.

To review your code, it would be good if your changes could be as small as
possible against the current mapsforge dev.

Is that possible that you rebase your code on current mapsforge dev and
generate a pull request from that?

Depending on how you manage your code base, it could be as easy as pulling
from origin and then rebase.

Ludwig

**Comment by devemux86** [comment]
Thanks for the PR, is it a Samples example?

As Ludwig mentioned, any patches or PR should be based on latest dev,
with the displayed commits to be only for the new code changes.

For that it's better the commits to be also squashed, in order to avoid the clutter in repository and have only the finally changed files together.

That way it would be easy for us to review the code and check the functionality.

You can read more about this (along with the squash method) here:
https://groups.google.com/forum/#!topic/mapsforge-dev/AK3yjjd8E6s

**Comment by devemux86** [comment]
Checking a bit your commits, please also avoid pushing changes in Documentation that are related to your fork's site.

A hint for the PR is to make a clean branch per feature and work in that.

**Comment by vennekamp** [comment]
Thanks again for your fast replies and your advices. Unfortunately, I'm a little bit shot on time, i.e. currently I can't spend much on the 'cluster marker' topic.  Reading your replies I would like to take the time to take 'one step back' and to open a more general discussion on my PR.

My commit is a pure "sample example", no change on the library itself. My own work can be found here (the classes to do the clustering):
https://github.com/vennekamp/mapsforge/tree/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/markerclusterer 
And a sample to show it's functionality:
https://github.com/vennekamp/mapsforge/blob/master/Applications/Android/Samples/src/main/java/org/mapsforge/applications/android/samples/ClusterMapActivity.java 
Overall: It’s propose is to show how a maker clustering could be integrated. Now step bak: I think one could ask whether or not this needs to be integrated into our branch. 

Frankly speaking: On one hand side I like to give you back some code to your application (but together with the responsibility for it :-) ), on the other hand side then you need you maintain some more code then, which is not part of the library itself. 

So, I ask myself (and you): Is it better to keep this example in my branch or do you like to have it within your code repository?

I would be more than happy to give it to you in the desired format, but - as mentioned before - I just like to step back and come up with a more general question before doing so...

Just my 5 cents,

Martin

**Comment by devemux86** [comment]
It's worth mentioning that since there is copyrighted code from other sources too, we need to make sure it conforms with Mapsforge license (LGPL3).

It's a good idea to begin as an additional example in Samples, without altering the core library for start.

Then after reviewing we could integrate it better in Mapsforge library.

**Comment by devemux86** [comment]
I'm closing the PR for now.
We could review it in the future with a more clean code (Samples) example.

**Comment by devemux86** [comment]
BTW I opened issue #669 about maker clustering for not forgetting it.

**Comment by vennekamp** [comment]
OK. I was pretty busy with other things this summer, - but, I still have on
my list. :-)

Additionally, I'm not very experienced with git, i.e. know only the very
basic options.

Best regards,

Martin

2015-09-06 14:43 GMT+02:00 Emux <notifications@github.com>:

**Comment by devemux86** [comment]
I think the best course of actions is to fork latest dev, create a branch for working on this feature (IIRC it's a Samples example) and repost a clean minimal PR.

You may want to familiarize yourself with some GitHub guides, e.g. [fork-a-repo](https://help.github.com/articles/fork-a-repo/), [working-with-forks](https://help.github.com/articles/working-with-forks/).

**Pull request closed without merging**
