### PR TITLE
POI: Multiple patterns in filtered search

### PR DESCRIPTION
**Pull request by Gustl22**
Hello,
if you filter the poi-database by a pattern you can only use a specific one: e.g. "%name=carl%addr:postcode=111111%";
But the order of osm-tags is not guaranteed, and you'll have to create a second query to get all results. 

So i added a method with multiple patterns in AndroidPoiPersistenceManager, to support multiple subqueries on poi-data at the same time.

Sorry for the mass of commits, next time i'll use cherry pick command ;D

Sincerely,
Rebo

### CODE REVIEW

**Comment by Gustl22** [comment]
I hope u didn't start merging; found a bug, if pattern contains null element. Fixed it in last commit. Sorry for the imperfect pull-request.

**Comment by devemux86** [comment]
Thanks, I'll review it soon. :slightly_smiling_face:

**Comment by devemux86** [comment]
Could you create a new pull request based on latest master with just the updated classes in their own commit?

**Comment by Gustl22** [comment]
Yes of course ;)

**Pull request closed without merging**
