### PR TITLE
Fix invalid number of way nodes 0

### PR DESCRIPTION
**Pull request by lincomatic**
https://github.com/mapsforge/mapsforge/issues/645

### CODE REVIEW

**Comment by ludwigb** [comment]
Would be excellent if that fixes the problem.

My one concern is possibly invalid segment counts in polygons/multipolygons/relations.

Can I suggest that we test this with a few files first to see that this does not introduce any new problem?

**Comment by devemux86** [comment]
@lincomatic Thanks, I'll have a look at it later.

**Comment by devemux86** [comment]
@ludwigb +1

**Comment by devemux86** [comment]
I can confirm that the situation has been improved.
Though I still see (more rarely) the warnings in question.

**Comment by lincomatic** [comment]
Can you tell me how to reproduce the warning? I ran it with your sample dataset and didn't see a problem. Is there a specific tile?

**Comment by devemux86** [comment]
I updated my answer. :smile: 
I'm playing with a multiple-map setup and forgot to update all maps.

**Comment by devemux86** [comment]
I'm building regular country maps too, and not seen any new problem introduced.

Will continue the tests, if all go well we can think when we should merge the fix, since it's about the writer only.

**Comment by ludwigb** [comment]
I have merged it in. If there are no concerns, we should move it to master soon and also get it into 0.6

**Comment by devemux86** [comment]
@ludwigb +1

**Pull request merged**
