### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by vennekamp**
Hi, maybe you remember my previous pull request on a Cluster Algorithm for mapsforge: https://github.com/mapsforge/mapsforge/pull/625 

Finally, I (hopefilly sucessful) did rebase the code and now I am able to send you the cleaner pull request for some new classes and some changed files. 

Please Review and comment & for your patience.

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks for the contribution.
Unfortunately (as you see above) the PR has been implemented in a way that's difficult to parse and accept.

I suppose you have the changes collected somehow in your code.
Try creating a clean local branch from latest dev and perform the changes in a few commits commits.
Also for updating your repository with dev, always perform rebase and never merge, to avoid all this confusion.

**Comment by vennekamp** [comment]
OK, I will recreate the commit. It comes all with more pitfalls than expected. :-(

**Comment by devemux86** [comment]
I may seems difficult at first but we're here to help. :smile: 

The purpose is having **clean minimal** PR, it's good for project's maintainability (and we can check more easily the changes).

I can clear the code but that eventually will take time and postpone the PR.

**Comment by vennekamp** [comment]
So, soon you will see my next try...
Am 10.10.2015 14:58 schrieb "Emux" <notifications@github.com>:

**Pull request closed without merging**
