### PR TITLE
high resolution mapsforge logo

### PR DESCRIPTION
**Pull request by Gustl22**
add mapsforge logo as vector drawable and update `ic_launcher` icon in android samples

### CODE REVIEW

**Comment by devemux86** [comment]
Can you add also mapsforge svg without the label?

**Comment by Gustl22** [comment]
Yes, to the ` docs/images/logo` directory then?
If you want I can add Photoshop file (with shadow for Android icons) there, too?

**Comment by devemux86** [comment]
Like the VTM logo svg without label in https://github.com/mapsforge/vtm/pull/508/commits/cbb357c1be16934568a7d0fab45234b9c61e3917, I'll slightly relocate them anyway.

**Comment by devemux86** [comment]
Thanks, nice work!
Squashed and merged via 5744f120541548daa978493794682016889daf8e.

Included only the svg in docs, as much larger eps could not be needed?

**Comment by Gustl22** [comment]
> Included only the svg in docs, as much larger eps could not be needed?

eps is easier to edit (with layers), but not needed ;)

**Pull request closed without merging**
