### PR TITLE
Faster parent tile drawing

### PR DESCRIPTION
**Pull request by cpt1gl0**
Make parent tile drawing faster by using Android canvas draw bitmap method for transforming the parent tile.

### CODE REVIEW

**Comment by cpt1gl0** [comment]
I think the only thing missing is an implementation of the newly introduced bitmap draw method in AWT canvas.

**Comment by devemux86** [comment]
> I think the only thing missing is an implementation of the newly introduced bitmap draw method in AWT canvas.

Indeed, or else the library cannot be built and should work in all supported platforms.

**Comment by devemux86** [comment]
Thanks, from some quick tests on Android emulator cannot see any _clear_ performance change?
Need to implement on Desktop too, so we can test easier the changes there.

Also `TileLayer` cannot be compiled, it has missing imports.

**Comment by cpt1gl0** [comment]
I added the missing includes and implemented srd/dst bitmap drawing for the AWT canvas.

**Comment by devemux86** [comment]
Thanks for the fixes. Still cannot see any notable performance benefit?
But there is regression in parent tiles rendering, now there are seams among them.
That comes because of the loss of precision in new draw methods (casting to `int`).

**Comment by devemux86** [comment]
tiles

**Comment by cpt1gl0** [comment]
I also hardly notice any difference on my mobile phone, but on the phone of my girlfriend it really gets irresponsive for ~1 second. I think it might be a memory issue. I guess the matrix transformation needs more memory than the simple just copying pixels from a certain area.
I am not sure if the seams are because of the rounding. Could you send me, or point me to some example code where I can easily see them?

**Comment by devemux86** [comment]
Cannot see anything with current `master`, though with the PR the change is immediately seen with first quick tests.

Like mentioned in previous PR we can add an option in `Parameters` for anyone wanting to skip parent tiles rendering if that's the way for speed increase.

**Comment by cpt1gl0** [comment]
I think the reason for the seams is the interpolation done when scaling the sub-regions of the parent tile. For the original approach there are no seams because the parent tile is scaled as a whole.

In the latest commit I disabled anti-aliasing and bilinear interpolation for parent tile scaling and would expect the seams to be gone now. - It would be great if you could check again. In addition, with interpolation disabled for parent tile drawing I notice another slight increase of rendering performance on my phone.

**Comment by devemux86** [comment]
Disabling such filters makes rendering worse / pixelated - not wanted for many users - for possibly gain a little performance on some devices. Cannot force such default behavior to all users.

If don't want parent tiles rendering, best is to make it optional, so can users are free to select their way.

**Comment by devemux86** [comment]
For fast rendering with extra features like rotation / tilt, better see an OpenGL map library like [VTM](https://github.com/mapsforge/vtm).

**Comment by cpt1gl0** [comment]
Would you be fine with having it optional so users can choose between "no parent tile rendering", "fast parent tile rendering" and "full parent tile rendering"?

**Comment by devemux86** [comment]
Simplest solution is an on / off switch, for anyone needing that workflow.
Pushed `Parameters.PARENT_TILES_RENDERING` option via 08db3cfe344dcfe53cbd08e5c3cbcd9c1ecacd01.

**Comment by cpt1gl0** [comment]
That's for sure simpler and good to have. Still, I'd prefer to have "fast" parent tiles instead of no parent tiles at all. Would you be fine with an additional parameter FAST_PARENT_TILES_RENDERING to enable the fast rendering algorithm?

**Comment by devemux86** [comment]
Implementation will become more complicated for minimum benefit (still cannot see any greater performance).

We can accelerate the whole map rendering if disable every possible anti-aliasing everywhere in lib, that does not solve the fact that some devices have issues, the solution is [accelerated rendering](https://github.com/mapsforge/mapsforge/pull/1101#issuecomment-464627019), not reduce map quality.

**Pull request closed without merging**
