### PR TITLE
Hillshading

### PR DESCRIPTION
**Pull request by usrusr**
Open todos:

1. Alignment is sometimes off
2. unfiltered upscaling is on Android 
3. the conversion from height values is just placeholder quality
4. The decision between AwtLuminanceShadingComposite and AlphaComposite should either be properly exposed to client applications (or themes) or it should go (properly hardcoded, without pretensions of flexibility). Without a consistent implementation on the Android side I would suggest staying with alpha blending on both sides (I would personally prefer luminance blending, since I expect it to work better with existing themes)

### CODE REVIEW

**Comment by usrusr** [comment]
alignment and unfiltered upscaling on android are fixed with latest commit (by switching from matrix-contolled scaling to src-rect/dest-rect controlled scaling), sorry for being a moving target

**Comment by devemux86** [comment]
I'd like to parse the PR and for some improvements like code formatting, new methods order and rebase / squash in a new branch, to be able to work there.
Have you other immediate work to push or PR will be quiet for sometime?

**Comment by usrusr** [comment]
I expect work on todo.3 (better hgt to shading) to be pretty much self-contained in a new implementation of o.mf.m.layer.hills.ShadingAlgorithm so it will smoothly merge with any changes you make to the stuff in the current PR. I'll just do it in a new branch so that I can keep the merging effort with your changes to the current PR on my side.

**Comment by devemux86** [comment]
I'll push this PR and any of my improvements in a new `hillshading` branch for users to start playing with it.
Then you can fetch it and post any new changes in that branch as new future PR, in order to update that.

BTW you can use GitHub markdown [task lists](https://guides.github.com/features/mastering-markdown/) in your first comment to indicate the completed tasks.

**Comment by devemux86** [comment]
Rebased, squashed and merged in [hillshading](https://github.com/mapsforge/mapsforge/tree/hillshading) branch via f66021f3fd868e4cf0d3346b2c69c42ce0275772, with minor improvements via 16be7063cf4613cb1285f7d4c21a311ec4bd75d0.

Can you post any future PR work on that branch?

**Comment by devemux86** [comment]
Since regular Mapsforge API can continue as usual and for broader user visibility..
I rebased, squashed and merged via 7dd483c991221543ff77c24588d017a42050e1b9, with minor improvements via 1928ec964c8f843e9dbc75cf7a0b3b638a93ee1e.

I included the hillshading rules in new [renderTheme-v6](https://github.com/mapsforge/mapsforge/blob/master/resources/renderTheme-v6.xsd) XML schema definition.
Also on Desktop Samples the 1st argument can be used as `dem` folder.

**Pull request closed without merging**
