### PR TITLE
Add group marker which handles markers with same gps location

### PR DESCRIPTION
**Pull request by mapicke**
Group marker have list with submarker. Click on group marker shows all children on a spiral.

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, does it involve marker clustering?
Could you add a Sample example for easy testing?

**Comment by devemux86** [comment]
As a general remark for pull requests, please keep the changes to a minimum and strictly related to the proposed feature / fix.
Unrelated code formatting (e.g. `final`, `this`) or comments should be avoided, as they complicate pull request's review. :slightly_smiling_face:

**Comment by devemux86** [comment]
Could you add the example in Android Samples?
Desktop Samples is just an example for Mapsforge in Java, not meant to be expanded.

**Comment by mapicke** [comment]
Yes, I will add a android sample. Please give some days to setup android studio.

Sorry for code formatting. Did not deactivate format on save.

**Comment by devemux86** [comment]
Take your time, probably create a new clean pull request(?). :slightly_smiling_face: 
BTW it's [recommended](https://help.github.com/articles/about-pull-requests/) using a topic branch for each pull request, for your easier maintenance.

**Comment by mapicke** [comment]
Ok, will create a new one :)

**Comment by devemux86** [comment]
Had a look at the example and code, working ok!
There has to be a cleanup and reorganization, those cyclic dependencies of the markers do not appear a good approach.
Also could you explain the fixed numbers for the spiral, don't they need to be dpi dependent?

**Comment by mapicke** [comment]
Added a fix for cyclic dependencies.
I just played around with apples grapher to draw the spiral. The calculation of the radius and theta should not be dpi dependent. But I will have some tests on it.

**Comment by devemux86** [comment]
Squashed and merged via 8f8ab24d33dd6995a437fac40a9c8d31014f45d8 with some improvements.

Implementation seems not generic, needs more parameters, various improvements, e.g. text not centered, etc.
So until we improve it further to meet library's standards, I have added in Samples as an example for users to test.

**Pull request closed without merging**
