### PR TITLE
Customizable zoom controls.

### PR DESCRIPTION
**Pull request by schildbach**
It now allows for vertical arrangements and customization of the button drawables. Gravity can now use any of the Gravity constants. Also, zoom speed of the buttons is configurable.

The samples are extended to show modern vertically arranged zoom controls and a screen density-aware position of those controls.

It now uses standard framework mechanisms to layout the controls. For this, MapActivity had to be switched to subclass FrameLayout rather than just ViewGroup.

Feel free to give it a whirl in the samples and let me know what you think.

device-2015-09-19-132202

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks will check it.

Though moving ```MapView``` from ```ViewGroup``` to ```FrameLayout``` is not something desirable.

We're going away from something generic (breaking users experience). There has to be a way to use ```ViewGroup``` for hosting like works now.

**Comment by devemux86** [comment]
BTW a convenient way for custom zoom controls (and our advice to users) was always hosting ```MapView``` in another layout and add on top the controls with the desired placement.

**Comment by schildbach** [comment]
Well, of course you can implement a ViewGroup too, but you'd end up duplicating FrameLayout. Why not use the Android framework?

**Comment by devemux86** [comment]
Because it's more limiting and just for one use and specially for components which cannot be included in the library anyway (so few will use it).

Imagine if someone else may need it as ```RelativeLayout```.
And in #680 we may change our opinion again.

And to prevent reactions, *Mapsforge intention is not becoming Android Library or AAR*, we prefer our current jar universal state.

**Comment by schildbach** [comment]
I just pushed a change that adds a convenient setControlOrientation() for the four possible combinations of orientation and which of the two controls comes first.

**Comment by devemux86** [comment]
A friendly reminder, it's better [discussing](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md#how-to-contribute) first the development of new features or changes.

We appreciate your effort, and so it will not be spent on things that eventually we may be unable to apply.

**Comment by schildbach** [comment]
I appreciate the reminder. However, I need those thing I implement anyway. The reason I'm using pull requests is because mapsforge is free software, and I thought it's only fair to contribute back.

**Comment by schildbach** [comment]
Ok, I will try to use ViewGroup rather than FrameLayout.

**Comment by devemux86** [comment]
>However, I need those thing I implement anyway.

That's understandable, but you need to see also that we have to keep Mapsforge as generic as possible for all users out there and more importantly not breaking their current API experience.

>The reason I'm using pull requests is because mapsforge is free software, and I thought it's only fair to contribute back.

Please keep them coming!

**Comment by devemux86** [comment]
(Analyzing the PR)
* Let's keep existing ```MapZoomControls``` class intact without altering its structure with foreign interferences or hacks (also there are many using it *as is*).
* We can have a new class (e.g. ```CustomZoomControls```) with the proposed functionality (still playing with current ```MapView```).

**Comment by schildbach** [comment]
I'm wondering will you actually post your analysis?

**Comment by schildbach** [comment]
I just reworked this PR so that MapView is still a ViewGroup (rather than FrameLayout) and rebased on current dev.

**Comment by devemux86** [comment]
Thanks.
* We can move customizable zoom controls into their own class (leaving default *as is*) and keeping only their code
* Use an ```enum``` way switching among those similar components
* Preferably the layout should be handled by the children, like was already implemented (we'll see for #699)

**Comment by devemux86** [comment]
Merged 004dff4ea9133e8b5d4c899946941893dae06b0d.

**Comment by schildbach** [comment]
Great, thanks for merging!

**Comment by ludwigb** [comment]
Should we not also have drawables for other densities than hdpi?

**Comment by devemux86** [comment]
>Should we not also have drawables for other densities than hdpi?

Yes having zoom drawables >```hdpi``` would be useful nowadays.

IIRC these drawables exist only in ```hdpi``` ?
(they have also their horizontal equivalents)

**Comment by schildbach** [comment]
@ludwigb Since it's only horizontal and vertical lines it doesn't matter much. Also, it's only a sample. (The other samples use hdpi only as well.)

**Comment by applantation** [comment]
I thought you cared about individual pixels? 😉.

Ok, maybe no issue.

**Comment by schildbach** [comment]
:smirk:

**Pull request closed without merging**
