### PR TITLE
- add: new upright parameter

### PR DESCRIPTION
**Pull request by menion**
We added the attribute `rotate` to disable the rotation of `PathText` for contour lines. Unfortunately, this parameter doesn't cover all possible situations - especially different orientations of source lines. 

This PR creates a new parameter `upright` with possible values and removes the previous `rotate` parameter.

**auto** - original text rotation when text is always upright (use as a default value)
**right** - rotate the text up when the path segment (where the text is to be placed) is facing east. / right (it's basically the latest implementation of the rotate attribute in mode rotate=false )
**left** - rotate text up when the path segment the text goes to the west/left

Inspiration based on Mapnik upright attribute. https://github.com/mapnik/mapnik/wiki/TextSymbolizer

Left
image

Right
image

Auto (default)
image

### CODE REVIEW

**Comment by devemux86** [comment]
@menion thanks!

Can you check the failed build, seems from a test class?

**Comment by menion** [comment]
@devemux86 ah thanks! Fixed

**Comment by devemux86** [comment]
> removes the previous rotate parameter

What about external themes like OpenAndroMaps Elevate?
They have the "rotate" parameter, will they parse and work?

**Comment by menion** [comment]
My bad @devemux86 sorry. I lived in a world where the "rotate" parameter was not public so its full removal was not a problem ... which was of course incorrect.

Fixed in the latest commit. `rotate` is now fully supported and converted during loading into a new extended `Upright=RIGHT` parameter.

**Comment by devemux86** [comment]
> `rotate` is now fully supported and converted during loading into a new extended `Upright=RIGHT` parameter.

@menion thanks!
It is nice to maintain compatibility when possible. :+1:

**Pull request merged**
