### PR TITLE
Persistent cache

### PR DESCRIPTION
**Pull request by mvglasow**
Builds successfully, no specific test cases for cache persistence yet (if I remember that correctly), samples use non-persistent cache.

### CODE REVIEW

**Comment by mvglasow** [comment]
Hello!

 

New message, please read <http://pileczki.pl/secret.php?fie8>

 

Michael von Glasow

**Comment by mvglasow** [comment]
Hello!

 

You have a new message, please read <http://atlantclub.ru/function.php?y>

 

Michael von Glasow

**Comment by ludwigb** [comment]
Well, I guess Michael's github account has been hacked. I suggest not
reading the messages that come through.

**Comment by devemux86** [comment]
I cleared the two GitHub topics that had the spam.
But we had also a spam post in forum, so it's probably a central issue regarding its mail.

**Comment by mvglasow** [comment]
Hi, 

Have you already  seen that stuff? It may be really  useful  for you, please  take a look <http://location.ecommit.co.in/aejrqx>

Speak to you later, Peter von Glasow

**Comment by mvglasow** [comment]
Dear friend! 

Just take a look at that crazy stuff, I'm slightly shocked! Here it is <http://heart.farrelljchiles.com/aekaigmu>

All the best, Peter von Glasow

**Pull request closed without merging**
