### PR TITLE
Hill shading: Bicubic interpolation

### PR DESCRIPTION
**Pull request by Sublimis**
- High resolution / high quality implementation of `StandardClasyHillShading`. It doubles the number of pixels on each axis and uses bicubic interpolation to achieve the best visual results.

## Sample preview (3" data)

High quality (bicubic/new):

bicubic-1 bicubic-2

Standard quality (bilinear/old):

bilinear-1 bilinear-2

### CODE REVIEW

**Comment by devemux86** [comment]
@Sublimis thanks, nice images, I will check it!

It also contains the multi thread read that was discussed [here](https://github.com/mapsforge/mapsforge/pull/1543#issuecomment-2381570846).

**Comment by Sublimis** [comment]
> @Sublimis thanks, nice images, I will check it!
> 
> It also contains the multi thread read that was discussed [here](https://github.com/mapsforge/mapsforge/pull/1543#issuecomment-2381570846).

Yes, everything is in there

**Comment by devemux86** [comment]
@Sublimis 

Is this the last part of the hillshading work?

I ask to know if a new Mapsforge version can be prepared.

**Comment by Sublimis** [comment]
@devemux86 

Yup, yes, nothing more regarding hill shading is planned in foreseeable future 👍 This last part was especially involving, but now hill shading bitmaps of theoretically any resolution and theoretically the best possible appearance (for the given data set) can be made by anyone by computing more bicubic points with the included method (double resolution algorithm is implemented in this PR).

**Comment by Sublimis** [comment]
@devemux86 

Thank you! 👍 💪

**Pull request merged**
