### PR TITLE
Fix LatLongUtils.zoomForBounds() can return negative values, #678

### PR DESCRIPTION
**Pull request by schildbach**
I got -1 from that method so I decided to fix the sanity check.

### CODE REVIEW

**Comment by devemux86** [comment]
I see we already perform value restriction, with min=0.
So we need to check why -1 managed to be returned.

**Comment by schildbach** [comment]
Math.min doesn't work because it doesn't catch wrapovers from the byte conversion.

**Comment by devemux86** [comment]
Do you have an example (to include also in test class) ?

**Comment by devemux86** [comment]
BTW let's open an issue for this, and then solve it.
That way people would know what's fixed.

**Comment by schildbach** [comment]
E.g. if the result of Math.max(...) would be 255, the narrowed byte value would be -1.

**Comment by devemux86** [comment]
I see what you mean, that could be solved by casting ```(byte)``` the ```floor``` result, but if/then works too.

**Comment by devemux86** [comment]
Fixes #678.

**Pull request merged**
