### PR TITLE
Introduce Path.isEmpty().

### PR DESCRIPTION
**Pull request by schildbach**
It's useful because I often write constructs like

```
for (Point point : points)
{
    if (path.isEmpty())
        path.moveTo(point);
    else
        path.lineTo(point);
}
```

### CODE REVIEW

**Comment by devemux86** [comment]
Please any PR should posted on dev branch (it's our workbench), see also [here](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Developers.md#how-to-contribute).

**Comment by devemux86** [comment]
Forgot to say thanks for the PR!

Also try keeping the methods sorted (old Mapsforge policy).

**Comment by schildbach** [comment]
Done.

**Comment by devemux86** [comment]
This PR cannot be used, it's always based on master and now even the commits are multiplied / mixed.

I recommend creating a new local branch based on latest dev, make the needed changes and post a new PR with a simple commit having only the PR code changes.

**Comment by schildbach** [comment]
Well its a bug of GitHub. If you look at the branch with the git command line tool, you'll see its based on your dev branch. But if you insist, I open a new PR.

**Comment by devemux86** [comment]
BTW we had mentioned some PR [instructions](https://groups.google.com/forum/#!msg/mapsforge-dev/-u0oRcuz9Ms/hO8qr81TDgAJ) also in forum, I'll update our docs at first chance.

**Pull request closed without merging**
