### PR TITLE
Allow 'Downloading Mapnik' sample to run even without germany.map,  #692

### PR DESCRIPTION
**Pull request by schildbach**

### CODE REVIEW

**Comment by devemux86** [comment]
Nice catch!
Just overriding the ```getInitialPosition``` wouldn't do the job?

**Comment by schildbach** [comment]
Yes, you're right. I amended the PR.

btw. The checks failed because apparently you enabled Travis but this branch doesn't have the Travis configuration yet.

**Comment by devemux86** [comment]
No I have not played with Travis (I don't know if @ludwigb did).

**Comment by devemux86** [comment]
Thanks.

**Comment by devemux86** [comment]
BTW for fixes / features please create first an issue (if we don't have already) and put its number on PR title (like I edited above).
So we may watch the issues progress and their linking with the PR(s).

**Comment by schildbach** [comment]
Actually on GitHub issues and pull requests are almost the same. You can assign PR to milestones and labels just as issues. Opening two tickets for each work items feels very redundant to me.

**Comment by devemux86** [comment]
An issue can have many linked PR and/or commits and we prefer watch the progress in issues list.

Also a PR can be rejected for various reasons, so a feature conversation should be located in its issue.

**Comment by ludwigb** [comment]
That was me, the build only failed because at that moment there was no
travis.yml file. This has been fixed.

**Pull request merged**
