### PR TITLE
Interface for MapViewPosition, …

### PR DESCRIPTION
**Pull request by mikes222**
- Interface for MapViewPosition
- alternative implementation AnimationQueueMapViewPosition with Animator queue, 
- Listener interface for manual move- and zoom-actions

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, will check it!
From a quick look I see some unrelated changes, like new overlays or overlay changes which should exist in their own PR, or exposing variables / methods as `protected` which should be avoided without reason.
New functionality can be selected easier via a flag in [Parameters](https://github.com/mapsforge/mapsforge/blob/master/mapsforge-core/src/main/java/org/mapsforge/core/util/Parameters.java) class, like all other features.
Also can you rebase / merge first on latest master?

**Comment by mikes222** [comment]
You are right, I have included these features:


* Interface for MapViewPosition
* Alternative implementation `AnimationQueueMapViewPosition ` with Animator queue,
* Listener interface for _manual_ move- and zoom-actions to recognize if the USER moves or zooms the map
* reverse iterator for Layers because I had IndexOutOfRangeExceptions at onTap() when layers are changed while `onTap`() was performed.
* `Polygon`/`Polyline`: Removed graphicFactory and made Path an instance variable to save memory and cpu
* `Rectangle` introduced: A special form of Polygon

Sorry for the bunch of features. These are the most important changes I made during the last months. I promise to make the next pull requests easier.

**Comment by devemux86** [comment]
> These are the most important changes I made during the last months. I promise to make the next pull requests easier.

Cannot merge mass collected features in library all together, it isn't safe or wise for repository history.
Need to have them split PR and proceed step by step for easy testing of each one separately.

**Comment by devemux86** [comment]
@mikes222 

Just a friendly reminder, wishing to merge those features, please post new [multiple simple pull requests based on latest master](https://github.com/mapsforge/mapsforge/blob/master/.github/CONTRIBUTING.md) with each feature strictly alone in its own separate pull request.
That way we could review and test them properly. :slightly_smiling_face: 

Leaving it open for now..

**Comment by mikes222** [comment]
Hi @devemux86 Sorry, I had no time up to now. I will send the improvements when I do have enough time to create all the pull requests. You can close this if you wish.

**Comment by devemux86** [comment]
Ok closing, please post separate pull requests for each feature based on latest master.

**Pull request closed without merging**
