### PR TITLE
mapsforge-map-writer: add places of worship as areas

### PR DESCRIPTION
**Pull request by Gustl22**
Until now only nodes are stored as place of worship. So churches and similar not were discernible.
Now areas are displayed too. Also plan to support more ways/areas incl. symbols in VTM.

### CODE REVIEW

**Comment by applantation** [comment]
Last time I checked there were a couple more religions that should also
make it into this patch.

But on a more general level, there used to a an osmosis plugin area2points
that added a point into the middle of a closed way.
https://wiki.openstreetmap.org/wiki/Osmosis/Detailed_Usage_0.40#--areapoints_.28--a2p.29

This has been, for unknown reasons, dropped from osmosis, but the code
exists and it is simply a question of installing the extension with osmosis
to get it to work.

I think this would be a better way of doing this, as it will mean on the
rendering front we do not require another rule for
churches/temples/mosques/ that appear as closed ways in OSM data.

**Comment by devemux86** [comment]
The religions in the PR are the same as the old ones in <pois> section.
They're been there from start, but eventually all should be improved.

Regarding the plugin seems a nice idea. Though it implies that users will know and use it.
And a perfect map creation should use definitely TagTransform (like OpenAndroMaps).
Here we try to offer just the a default tag-mapping for general purposes.

**Comment by devemux86** [comment]
Thanks!

**Comment by devemux86** [comment]
I updated tag-mapping with more values as exist already in the themes and with available symbols in resources.

**Comment by devemux86** [comment]
Note: in v5 maps such issues should be solved now with variable tag values!

**Comment by Gustl22** [comment]
> _Ludwig:_ But on a more general level, there used to a an osmosis plugin area2points that added a point into the middle of a closed way.

Yes, providers should consider area2points and TagTransform. But then we need a guide, that all can get the same results.

> _Ludwig:_ I think this would be a better way of doing this, as it will mean on the rendering front we do not require another rule for churches/temples/mosques/ that appear as closed ways in OSM data.

No need of duplicate rules for nodes and ways, if we handle each `value` for ways and nodes in one step. Will post a PR in VTM.

> _devemux86:_ Note: in v5 maps such issues should be solved now with variable tag values!

What issues do mean?

**Comment by devemux86** [comment]
> What issues do you mean?

The possible missed values for a tag, can be solved with new variable tag values feature, like we do now in buildings (for v5 maps).

**Comment by devemux86** [comment]
There is already support in map-writer #886 for automatic areas-to-points calculation to be used for labels / symbols. Can be enabled:
- globally via [label-position](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md#advanced-options-only-use-when-you-know-what-you-are-doing) option
- in tag-mapping via [label-position](https://github.com/mapsforge/mapsforge/blob/master/resources/tag-mapping.xsd#L127-L134) attribute

VTM https://github.com/mapsforge/vtm/issues/80 already supports this feature. Not Mapsforge #891.

Though all these need improvements, so are disabled by default.
See issues in map-writer #930 and VTM https://github.com/mapsforge/vtm/issues/402.

**Pull request merged**
