### PR TITLE
Android gestures

### LINKED ISSUE #219: Add kinetic scrolling to the MapView
_From [thilo.mu...@gmail.com](https://code.google.com/u/109067824594513388759/) on January 07, 2012 17:07:11_

Currently the map stops immediately when a move gesture is aborted. We should also support for kinetic scrolling, where the map is moved for a small time with a configurable attenuation.

This issue was originally part of issue 19 .

_Original issue: http://code.google.com/p/mapsforge/issues/detail?id=219_

### PR DESCRIPTION
**Pull request by schildbach**
The goal of this PR is get native Android look and feel when it comes to panning and zooming. Please feel free to try it in the example app and leave comments.

Open issues / questions:

- I removed MapView.setGestureDetector(), because it's not clear how it should interact with existing gestures. It wasn't used by any of the examples. (:thumbsup: added it back)
- Where does all this flicker come from? Especially with zooming, it's really ugly. It's present on current dev and released versions as well, so it's not a regression of my patch. Still I'd like to investigate more, maybe we can fix it in one go. (:thumbsup: almost fixed)
- Need to test edge cases, like flinging off boundaries of the map. (:thumbsup: tested, works)
- Flinging causes a lot of tile downloads for server-based maps. Apparently some of the servers are rate limited, leading to white tiles. (:thumbsdown: white tiles seem to be caused by hardware acceleration)
- Currently there is no configuration of the fling properties, and long tap delay isn't configurable any more. (:thumbsup: not needed, it will use OS defaults)

Fixes #219.

### CODE REVIEW

**Comment by devemux86** [comment]
>I removed MapView.setGestureDetector(), because it's not clear how it should interact with existing gestures. It wasn't used by any of the examples.

Don't remove Mapsforge functionality. Because it's not used in Sampes it does not mean users don't use it at all!

**Comment by devemux86** [comment]
>Where does all this flicker come from? Especially with zooming, it's really ugly. It's present on current dev and released versions as well, so it's not a regression of my patch. Still I'd like to investigate more, maybe we can fix it in one go.

Have you disabled [hardaware acceleration](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Android-App.md#hardware-acceleration) ?

In master Samples we have it disabled, in dev Samples enabled/

**Comment by devemux86** [comment]
(I refactored Mapsforge gesture system lately, but it could use a new simpler implementation)

If we're going to change its structure, first we have to make sure that all current functionality works again, then add new features.

I'll examine the PR in detail the next days.

**Comment by schildbach** [comment]
The flickering isn't caused by hardware acceleration. It's caused by zoom animation(s) running in parallel to the gestures themselves. I'm currently fixing scale gestures as well, it'll take today or maybe tomorrow.

**Comment by devemux86** [comment]
Thanks, that's good to know.
BTW in Mapsforge we support minimum Android 2.3, so any new API should be able to play there too.

**Comment by devemux86** [comment]
I opened issue #688 about that (better the conversation to be there).

Also I don't know if you're aware of [Android Gesture Detectors](https://github.com/Almeros/android-gesture-detectors) framework.

**Comment by schildbach** [comment]
Ok, this PR is now much closer to going into thorough review. I tried to not touch MapViewPosition too much, but it was inevitable to add overloaded methods that disable animations entirely.

There is some remaining jaggies with the pinch gesture, but IMHO it's much better than before.

Feel free to give it a spin in the sample app!

**Comment by devemux86** [comment]
Thanks @schildbach I will!

**Comment by devemux86** [comment]
@schildbach first impression is positive!
Need of course work for various artifacts, I'll examine also the code changes.

**Comment by devemux86** [comment]
Forgot to mention that ```setGestureDetector``` was added for cases like:
```java
mapView.setGestureDetector(new GestureDetector(Context, SimpleOnGestureListener));
```
where users can intervene and/or listen for a subset of the gestures.

**Comment by devemux86** [comment]
Concerning copyright notices: ```TouchGestureListener``` may be a new class, but stands on and actually contains code work from removed classes, so it must also preserves their copyrights.

**Comment by schildbach** [comment]
I added setGestureDetector() back and rebased on current dev.

**Comment by devemux86** [comment]
@schildbach is there more work to expect in the PR?

**Comment by schildbach** [comment]
@devemux86 Currently not. My todo list in the description is all checked and I believe I addressed your comments. I just rebased against dev again and checked nothing is broken.

**Comment by devemux86** [comment]
Ok I'll take a look.
(IIRC there were some issues with zoom)

**Comment by schildbach** [comment]
Yes there are. I believe they're related to the way we do zoom animations currently, see #688. Anyway, this PR is about the fling gesture.

**Comment by devemux86** [comment]
Thanks for the PR, it motivated us for a total overhaul of Mapsforge gestures. :smile: 
Merged 568fb0078cbdde9b0cc95ea63a1a79e911f52387 with additions of missing elements and various improvements / fixes.

**Pull request closed without merging**
