### PR TITLE
Feature: public map read result builder

### PR DESCRIPTION
**Pull request by muZZkat**
I need to write a custom MapDataStore so needed to create make the MapReadResult builder public.

I left the variables with no modifier so they could still be added directly by the package, I guess it would be better to mark them provide and make the package also access them via the getter/settings.

Did you want me to make this change?

### CODE REVIEW

**Comment by devemux86** [comment]
You mean ```private```, right?

>Did you want me to make this change?
Yes please do.

**Comment by muZZkat** [comment]
`private`, not `provide` :)

**Comment by ludwigb** [comment]
+1 for this change

**Comment by devemux86** [comment]
Also we can rename the ```setIsWater``` setter to ```setWater```, (variable's name confuses the generators).

**Comment by muZZkat** [comment]
OK. Should all be sweet.

**Comment by devemux86** [comment]
You did the rename via refactoring?
The ```setWater``` should be changed in all needed files.

Also could you squash the commits into one?
You can find instructions [here](https://groups.google.com/d/msg/mapsforge-dev/AK3yjjd8E6s/a6Ct5V7b-i8J), or I can do it if you find it difficult.

**Comment by muZZkat** [comment]
Never done that before. Learn something new every day. Commits have been squashed.

**Comment by devemux86** [comment]
We try to keep repository clean with the final commits. :)

Thanks for the PR.

**Pull request merged**
