### PR TITLE
Update Specification-Binary-Map-File.md

### PR DESCRIPTION
**Pull request by mjcross**
Add description of how double-delta encoding works in way data blocks, including sample code

### CODE REVIEW

**Comment by devemux86** [comment]
Thanks, some remarks:
- Can you post the code example in Java as it's library's main language?
- Also in fenced code blocks you can enable syntax highlighting (see [here](https://help.github.com/articles/creating-and-highlighting-code-blocks/))

**Comment by mjcross** [comment]
Hi there - yes, I thought that might be the case.... unfortunately I don't know how to write in Java! I only do 'C' and Swift :(

**Comment by devemux86** [comment]
Don't worry, on second thought simple [pseudocode](https://en.wikipedia.org/wiki/Pseudocode) would be the best solution, in order to keep the specific doc generic.
Do you want to try it?

**Comment by mjcross** [comment]
Sure, no problem I will convert it into pseudocode :)  Took me quit a bit of trial and error to work out how the 'double-delta' encoding had been implemented...  I have to go out soon so I will do it later or tomorrow. Now I have to work out how to edit my pull request... probably simplest if I close it and create a new one ?

**Comment by devemux86** [comment]
The simplest way may appear to close and create a new one.
But I suggest to take some time and experiment with amend / squash commits and force push in the pull request (search a bit online for all that). That way any possible changes / corrections can be easily integrated.

**Comment by mjcross** [comment]
Hmmm - I have made two edits to the file in order to change the code example from Swift to pseudo-code; and the pull request (on the github website) is now showing three commits. I haven't yet been able to find a way to 'squash' the commits - perhaps this is something that I would have to do via the command line 'git' tool?  Anyhow, I hope that you can see the final version of the file... :-/ apologies for my lack of experience with collaborative development tools, I've only ever really worked solo :)

**Comment by devemux86** [comment]
Thanks for taking care of it.

A very good article explaining the commits squash procedure is [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html).
If you want to try it, or I can do it at the merge process.

**Comment by devemux86** [comment]
@mjcross any news or should I merge / squash the PR?

**Comment by mjcross** [comment]
Hi there - sorry! I had a 'domestic priority override' (I.e. the new garage door remote control had to be fitted) so I did not get any more time to spend on it - yes please, if it is possible for you to merge/squash then thanks!

I can successfully decode all the tile features now by the way, coded in native Swift from scratch - I'm now working out the most efficient way to identify which tiles overlap the screen area: a very interesting problem especially when the view is rotated...

Martin

**Comment by devemux86** [comment]
Merged via 991f84d26aada054850d11021c985b177013a8ff.

**Pull request closed without merging**
