### PR TITLE
Pin and PinGroup

### PR DESCRIPTION
**Pull request by virus-warnning**
Add two classes Pin and PinGroup.

* Pin is a layer like Marker, but it doesn't need bitmap. 
* PinGroup is a container of Pin, and let all Pins work in single selection mode.

### CODE REVIEW

**Comment by virus-warnning** [comment]
pin-and-pingroup

**Comment by devemux86** [comment]
Thanks!
Some first notes:

- We better avoid creating paints in each `draw` call and instead pass them as parameters for performance.
- All fixed values (like sizes) in calculations better use the display model scale factor for playing well in all device densities.

e.g. you could check the [debug layers](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/debug) for how we handle such cases.

Also could you add an example in [mapsforge-samples-android](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-samples-android) to demonstrate the use of the classes?

**Comment by virus-warnning** [comment]
GraphicFactory.createPaint() seems return existed Paint.
When I create Paint to draw Pin, than Grid is also affected.

**Comment by devemux86** [comment]
> GraphicFactory.createPaint() seems to return existed Paint.

What existed? A new class is created with every `createPaint` call.
You can check the other layers in [overlay](https://github.com/mapsforge/mapsforge/tree/master/mapsforge-map/src/main/java/org/mapsforge/map/layer/overlay) package for how the paints are used.

> Is demo activity necessary in this pull request?

Well before merging something we have to test it first. :slightly_smiling_face: 
Also users will benefit from examples to see in action how new API works.
I can probably create the example later.

**Comment by virus-warnning** [comment]
Thanks, i'll review more to understand how overlay works.

**Comment by virus-warnning** [comment]
Is it possible to let paint support matrix, so that I can rotate pin against the azimuth.
Canvas just support drawBitmap() with matrix.

**Comment by devemux86** [comment]
What do you mean?
Paint just holds style and color information about drawing, which is performed by Canvas.

**Comment by virus-warnning** [comment]
Canvas.drawPath() & Canvas.drawCircle() cannot work with Matrix.

**Comment by devemux86** [comment]
Canvas calls are implemented per platform in `AndroidCanvas` and `AwtCanvas` using there each native platform API.
So besides `drawBitmap` are there any other platform draw methods that can use a `Matrix` (e.g. in [android.graphics.Canvas](https://developer.android.com/reference/android/graphics/Canvas.html))?

**Comment by virus-warnning** [comment]
https://developer.android.com/reference/android/graphics/Canvas.html#setMatrix(android.graphics.Matrix)

**Comment by devemux86** [comment]
That's something different and Android specific as it affects the whole Canvas instead of just the draw call.
If there is need we could see it separately in another issue as we need to implement it somehow for Desktop too.

**Comment by devemux86** [comment]
Closing due to lack of follow up.
Can post new PR with improvements.

**Pull request closed without merging**
